export interface ServiceCategory {
  id: string;
  title: string;
  categoryGroup: string;
  iconName: string;
  description: string;
  commonProblems: string[];
  priceRange: string;
  estimatedDuration: string;
  whatsIncluded: string[];
  badge?: string;
  popular?: boolean;
}

export const SERVICE_GROUPS = [
  'All',
  'Electrical & Cooling',
  'Plumbing & Water',
  'Appliance Repair',
  'Cleaning & Sanitization',
  'Carpentry & Woodwork',
  'Painting & Renovations',
  'Security, Tech & Power',
  'Shifting & Utility',
] as const;

export const HOUSEHOLD_SERVICES: ServiceCategory[] = [
  // Electrical & Cooling
  {
    id: 'electrician',
    title: 'Electrician',
    categoryGroup: 'Electrical & Cooling',
    iconName: 'Zap',
    badge: 'Popular',
    popular: true,
    description: 'Certified electrical repairs, short-circuit troubleshooting, wiring, circuit breakers, and lighting installations.',
    commonProblems: ['Frequent short circuits / tripped breakers', 'Burning smell or sparking outlets', 'Flickering lights and voltage fluctuations', 'New switchboard or heavy appliance wiring'],
    priceRange: '₹199 - ₹799 (Varies by city & work scope)',
    estimatedDuration: '30 - 60 mins',
    whatsIncluded: ['Safety inspection of main switch box', 'High-grade copper wiring check', 'Post-repair load test', '30-day service warranty'],
  },
  {
    id: 'ac-service',
    title: 'AC Service',
    categoryGroup: 'Electrical & Cooling',
    iconName: 'Wind',
    badge: 'Hot',
    popular: true,
    description: 'Comprehensive Split & Window AC servicing, jet wash cleaning, gas leak detection, and gas refilling.',
    commonProblems: ['AC not cooling or blowing warm air', 'Water leakage from indoor unit', 'Foul smell or loud noise from compressor', 'High electricity bill due to clogged filters'],
    priceRange: '₹499 - ₹2,499 (Varies by city & gas refilling)',
    estimatedDuration: '45 - 90 mins',
    whatsIncluded: ['High-pressure foam & jet wash of indoor/outdoor unit', 'Gas pressure & current check', 'Filter cleaning & drain pipe unblocking', 'Performance diagnostics'],
  },
  {
    id: 'fan-repair',
    title: 'Fan Repair',
    categoryGroup: 'Electrical & Cooling',
    iconName: 'RefreshCw',
    description: 'Ceiling fan, exhaust fan, and pedestal fan repair, capacitor replacement, bearing lubrication, and new installation.',
    commonProblems: ['Fan making squeaking noise or running slow', 'Wobbly fan blades', 'Capacitor burnout or motor heating', 'Remote control or regulator failure'],
    priceRange: '₹149 - ₹499 (Varies by city & parts)',
    estimatedDuration: '30 - 45 mins',
    whatsIncluded: ['Motor & capacitor check', 'Blade alignment & balancing', 'Regulator & wiring inspection', 'Noise reduction tuning'],
  },
  {
    id: 'cooler-repair',
    title: 'Cooler Repair',
    categoryGroup: 'Electrical & Cooling',
    iconName: 'Wind',
    description: 'Desert and personal air cooler repair, water pump replacement, honeycomb pad replacement, and motor servicing.',
    commonProblems: ['Water pump not circulating water', 'Fan motor not rotating or overheating', 'Bad odor from cooling pads', 'Water leakages from cooler tank'],
    priceRange: '₹249 - ₹699 (Varies by city & components)',
    estimatedDuration: '30 - 60 mins',
    whatsIncluded: ['Submersible pump testing', 'Cooling pad fitment check', 'Electrical motor insulation test', 'Internal tank cleaning'],
  },

  // Plumbing & Water
  {
    id: 'plumber',
    title: 'Plumber',
    categoryGroup: 'Plumbing & Water',
    iconName: 'Droplet',
    badge: 'Top Rated',
    popular: true,
    description: 'Expert plumbing repairs for leaking pipes, tap replacements, flush tank repairs, and sanitary fitting installation.',
    commonProblems: ['Continuous tap or pipe leakage', 'Low water pressure in shower/taps', 'Flush tank overflow or handle fault', 'Sink drain line clogging'],
    priceRange: '₹199 - ₹899 (Varies by city & materials)',
    estimatedDuration: '30 - 60 mins',
    whatsIncluded: ['Leakage detection & sealant application', 'Tap washer/spindle replacement', 'Pressure check of pipe lines', 'Post-service cleanup'],
  },
  {
    id: 'water-leakage-repair',
    title: 'Water Leakage Repair',
    categoryGroup: 'Plumbing & Water',
    iconName: 'AlertTriangle',
    description: 'Advanced thermal leak detection and structural pipe repair for hidden wall leaks, roof seepage, and ceiling dampness.',
    commonProblems: ['Damp patches or peeling paint on walls', 'Water dripping from ceiling', 'Unexplained high water bill', 'Moisture buildup around concealed pipes'],
    priceRange: '₹499 - ₹2,999 (Varies by city & damage scale)',
    estimatedDuration: '60 - 180 mins',
    whatsIncluded: ['Non-destructive leak detection test', 'Concealed pipe pressure testing', 'Seepage repair & waterproofing coat', 'Structural safety advice'],
  },
  {
    id: 'drain-blockage',
    title: 'Drain Blockage',
    categoryGroup: 'Plumbing & Water',
    iconName: 'RotateCcw',
    description: 'Heavy-duty drain unblocking using drain augers and pressure rodding for kitchen sinks, bathroom floor drains, and main sewer pipes.',
    commonProblems: ['Water backing up in sink or bathroom', 'Slow drainage with gurgling noises', 'Foul sewage odors', 'Main line grease buildup'],
    priceRange: '₹349 - ₹1,299 (Varies by city & pipe length)',
    estimatedDuration: '45 - 90 mins',
    whatsIncluded: ['Mechanical snake / pressure rod unblocking', 'Grease & debris clearance', 'Flow velocity testing', 'Disinfectant flush'],
  },
  {
    id: 'water-tank-cleaning',
    title: 'Water Tank Cleaning',
    categoryGroup: 'Plumbing & Water',
    iconName: 'Shield',
    description: 'Hygienic 6-stage deep cleaning and UV sanitization for overhead plastic/concrete water tanks and underground sumps.',
    commonProblems: ['Dirty or smelly tap water', 'Sediment & sludge accumulation in tank', 'Algae growth on tank walls', 'Contaminated water supply'],
    priceRange: '₹499 - ₹1,999 (Varies by tank capacity: 500L to 5000L)',
    estimatedDuration: '60 - 120 mins',
    whatsIncluded: ['Dewatering & sludge extraction', 'High-pressure jet cleaning', 'Anti-bacterial scrub & UV sterilization', 'Submersible pump rinse'],
  },
  {
    id: 'water-tank-booking',
    title: 'Water Tanker Booking',
    categoryGroup: 'Plumbing & Water',
    iconName: 'Truck',
    description: 'Prompt delivery of clean potable or commercial water tankers (3000L to 12000L capacity) directly to your home or building.',
    commonProblems: ['Municipal water supply shortage', 'Borewell dried up or under maintenance', 'Emergency water requirement for construction or events'],
    priceRange: '₹800 - ₹3,500 (Varies by tanker volume & distance)',
    estimatedDuration: 'Same Day Delivery (2 - 4 hours)',
    whatsIncluded: ['TDS & purity verified water delivery', 'Hose pipe connection up to sump/tank', 'Full volumetric delivery guarantee'],
  },
  {
    id: 'borewell-service',
    title: 'Borewell Service',
    categoryGroup: 'Plumbing & Water',
    iconName: 'Layers',
    description: 'Submersible pump repair, borewell flushing, compressor cleaning, and deep borewell flushing services.',
    commonProblems: ['Submersible pump motor burned out', 'Borewell pumping muddy water', 'No water flow from borewell', 'Control panel starter trip issue'],
    priceRange: '₹999 - ₹5,999 (Varies by depth & motor HP)',
    estimatedDuration: '2 - 5 hours',
    whatsIncluded: ['Pump pulling & motor health check', 'Compressor air-flushing of borewell', 'Control panel relay repair', 'Flow rate measurement'],
  },
  {
    id: 'plumbing-installation',
    title: 'Plumbing Installation',
    categoryGroup: 'Plumbing & Water',
    iconName: 'Wrench',
    description: 'Complete sanitary fitment for new homes, bathroom vanity installation, diverters, shower panels, and basin setups.',
    commonProblems: ['Setting up new sanitaryware', 'Upgrading old plumbing fixtures', 'Installing overhead water tanks & valves'],
    priceRange: '₹399 - ₹3,499 (Varies by fixture count)',
    estimatedDuration: '60 - 180 mins',
    whatsIncluded: ['Precision alignment & seal fitting', 'CPVC / PPR pipe joint solvent welding', 'Pressure test before handoff'],
  },
  {
    id: 'pipe-repair',
    title: 'Pipe Repair',
    categoryGroup: 'Plumbing & Water',
    iconName: 'Zap',
    description: 'CPVC, PVC, GI, and copper pipe repair, joint replacement, burst pipe emergency sealing, and valve fix.',
    commonProblems: ['Burst or cracked pipe line', 'Rusted metal pipe leakage', 'Leaking main inlet valve'],
    priceRange: '₹249 - ₹999 (Varies by pipe material & reach)',
    estimatedDuration: '45 - 90 mins',
    whatsIncluded: ['Damaged section replacement', 'Heavy-duty solvent/clamp sealing', 'Pressure resilience testing'],
  },

  // Appliance Repair
  {
    id: 'appliance-repair',
    title: 'Appliance Repair',
    categoryGroup: 'Appliance Repair',
    iconName: 'Wrench',
    popular: true,
    description: 'Multi-brand household appliance diagnostics and component repairs for all major home electronics.',
    commonProblems: ['Appliance not turning on', 'Unusual vibration or mechanical noise', 'Electrical error codes or short circuits'],
    priceRange: '₹299 - ₹1,499 (Varies by appliance & replacement parts)',
    estimatedDuration: '45 - 90 mins',
    whatsIncluded: ['Complete component diagnostic check', 'Original spare part replacement options', '90-day parts warranty'],
  },
  {
    id: 'ro-service',
    title: 'RO/Water Purifier Service',
    categoryGroup: 'Appliance Repair',
    iconName: 'Droplet',
    badge: 'Popular',
    popular: true,
    description: 'RO, UV, and UF water purifier maintenance, filter replacements, membrane cleaning, and TDS calibration.',
    commonProblems: ['Water tasting bitter or foul', 'Slow water flow from purifier', 'Water leaking beneath unit', 'Filter light or buzzer alarm ringing'],
    priceRange: '₹299 - ₹1,899 (Varies by filter kit replaced)',
    estimatedDuration: '30 - 60 mins',
    whatsIncluded: ['Sediment & carbon filter check', 'TDS water quality measurement', 'UV lamp & booster pump check', 'Sanitized tank cleaning'],
  },
  {
    id: 'refrigerator-repair',
    title: 'Refrigerator Repair',
    categoryGroup: 'Appliance Repair',
    iconName: 'Cpu',
    description: 'Single door, double door, and side-by-side fridge repair, gas charging, compressor repair, and thermostat replacement.',
    commonProblems: ['Fridge not cooling or freezer over-icing', 'Compressor continuously running or tripping', 'Water pooling under vegetables tray', 'Defrost heater/timer failure'],
    priceRange: '₹349 - ₹2,999 (Varies by issue & gas refilling)',
    estimatedDuration: '45 - 120 mins',
    whatsIncluded: ['Gas pressure & relay test', 'Evaporator coil inspection', 'Thermostat & door gasket seal check'],
  },
  {
    id: 'washing-machine-repair',
    title: 'Washing Machine Repair',
    categoryGroup: 'Appliance Repair',
    iconName: 'RefreshCw',
    description: 'Front load, top load, and semi-automatic washing machine repair, drum bearing fix, motor replacement, and error code troubleshooting.',
    commonProblems: ['Machine not spinning or draining water', 'Excessive shaking/bouncing during spin cycle', 'Water leakages underneath', 'Door lock or PCB error code display'],
    priceRange: '₹349 - ₹2,499 (Varies by spare parts & model)',
    estimatedDuration: '45 - 90 mins',
    whatsIncluded: ['Drain pump & belt check', 'Motor winding test', 'Drum suspension spring inspection'],
  },
  {
    id: 'tv-repair',
    title: 'TV Repair',
    categoryGroup: 'Appliance Repair',
    iconName: 'Tv',
    description: 'LED, OLED, QLED & Smart TV repair, display backlight bar replacement, motherboard fix, speaker repair, and wall mounting.',
    commonProblems: ['Sound working but screen is black', 'Vertical or horizontal lines on panel', 'TV stuck on startup logo', 'HDMI or power supply failure'],
    priceRange: '₹399 - ₹3,999 (Varies by screen size & PCB)',
    estimatedDuration: '45 - 120 mins',
    whatsIncluded: ['Backlight LED strip testing', 'Power supply board diagnostics', 'Display panel connection re-seating'],
  },
  {
    id: 'microwave-repair',
    title: 'Microwave Repair',
    categoryGroup: 'Appliance Repair',
    iconName: 'Flame',
    description: 'Convection, grill, and solo microwave repair, magnetron replacement, touchpad repair, and turntable motor fix.',
    commonProblems: ['Microwave running but food not heating', 'Sparking or burning noise inside chamber', 'Touchpad buttons not responding', 'Turntable glass tray not spinning'],
    priceRange: '₹299 - ₹1,499 (Varies by magnetron/PCB replacement)',
    estimatedDuration: '30 - 60 mins',
    whatsIncluded: ['High-voltage capacitor & diode test', 'Magnetron radiation safety check', 'Interlock door switch test'],
  },
  {
    id: 'geyser-repair',
    title: 'Geyser Repair',
    categoryGroup: 'Appliance Repair',
    iconName: 'Thermometer',
    description: 'Electric and gas water heater geyser servicing, heating element replacement, thermostat replacement, and tank descaling.',
    commonProblems: ['Water not heating or taking too long', 'Geyser tripping main circuit breaker', 'Water leaking from geyser body', 'Rusted orange water coming out'],
    priceRange: '₹299 - ₹1,299 (Varies by heating element/thermostat)',
    estimatedDuration: '45 - 75 mins',
    whatsIncluded: ['Heavy heating coil descaling', 'Thermostat auto-cutoff safety test', 'Pressure release valve test'],
  },
  {
    id: 'chimney-service',
    title: 'Chimney Service',
    categoryGroup: 'Appliance Repair',
    iconName: 'Wind',
    description: 'Kitchen chimney deep cleaning, baffle filter degreasing, motor servicing, and duct pipe installation.',
    commonProblems: ['Oil dripping from chimney onto stove', 'Low suction power despite high fan speed', 'Loud motor humming noise', 'Touch controls or auto-clean feature fault'],
    priceRange: '₹499 - ₹1,499 (Varies by deep cleaning vs repair)',
    estimatedDuration: '60 - 90 mins',
    whatsIncluded: ['Baffle & mesh filter chemical degreasing', 'Blower fan oil removal', 'Duct pipe seal inspection'],
  },
  {
    id: 'gas-stove-repair',
    title: 'Gas Stove Repair',
    categoryGroup: 'Appliance Repair',
    iconName: 'Flame',
    description: '2/3/4 burner glass top stove and cooking hob repair, burner cleaning, nozzle replacement, and gas pipeline leak fix.',
    commonProblems: ['Yellow/orange flame causing black soot', 'Gas burner not lighting up or click ignition faulty', 'Gas odor near stove knobs', 'Knobs stuck or loose'],
    priceRange: '₹199 - ₹699 (Varies by burner & valve count)',
    estimatedDuration: '30 - 60 mins',
    whatsIncluded: ['Burner orifice jet cleaning', 'Gas valve leak test', 'Auto-ignition spark plug check'],
  },

  // Cleaning & Sanitization
  {
    id: 'cleaning',
    title: 'Home Cleaning',
    categoryGroup: 'Cleaning & Sanitization',
    iconName: 'Sparkles',
    badge: 'Popular',
    popular: true,
    description: 'Full house deep cleaning including floor scrubbing, window wiping, cobweb removal, and cabinet dusting.',
    commonProblems: ['Dust & grime buildup in hard-to-reach areas', 'Post-party or festival house cleaning', 'Moving into a new rental home'],
    priceRange: '₹1,999 - ₹6,999 (Varies by home BHK layout)',
    estimatedDuration: '3 - 6 hours',
    whatsIncluded: ['Single disc floor machine scrubbing', 'Window glass & mesh deep washing', 'Bathroom & kitchen degreasing', 'Eco-friendly non-toxic chemicals'],
  },
  {
    id: 'deep-cleaning',
    title: 'Deep Cleaning',
    categoryGroup: 'Cleaning & Sanitization',
    iconName: 'Sparkles',
    description: 'Intensive deep sanitation for vacant or occupied apartments, balcony scrubbing, door polishing, and ceiling cleaning.',
    commonProblems: ['Post-construction dust and cement stains', 'Deep ingrained grease and limescale deposits', 'Tenant handover deep wash'],
    priceRange: '₹2,499 - ₹8,999 (Varies by total square footage)',
    estimatedDuration: '4 - 8 hours',
    whatsIncluded: ['Industrial vacuuming & steam sanitation', 'High-touch surface disinfection', 'Balcony & tile grouting wash'],
  },
  {
    id: 'sofa-cleaning',
    title: 'Sofa Cleaning',
    categoryGroup: 'Cleaning & Sanitization',
    iconName: 'Maximize',
    description: 'Fabric & leather sofa deep shampooing, dust mite extraction, stain removal, and conditioning.',
    commonProblems: ['Food/beverage stains on upholstery', 'Pet hair & odorous upholstery', 'Faded leather requiring polish & nourishment'],
    priceRange: '₹499 - ₹1,999 (Varies by seat count: 3 to 7 seaters)',
    estimatedDuration: '60 - 120 mins',
    whatsIncluded: ['Dry vacuuming & spot stain treatment', 'Organic shampoo injection-extraction wash', 'Upholstery quick-dry treatment'],
  },
  {
    id: 'carpet-cleaning',
    title: 'Carpet Cleaning',
    categoryGroup: 'Cleaning & Sanitization',
    iconName: 'Layers',
    description: 'Commercial & residential rug shampooing, deep pile dirt extraction, odor neutralization, and anti-bacterial spray.',
    commonProblems: ['Ingrained dirt in carpet fibers', 'Spilled coffee/wine spots', 'Musty damp carpet smell'],
    priceRange: '₹399 - ₹1,499 (Varies by carpet area sq ft)',
    estimatedDuration: '45 - 90 mins',
    whatsIncluded: ['Heavy vacuuming & foam agitation', 'Deep moisture extraction', 'Deodorizing treatment'],
  },
  {
    id: 'bathroom-cleaning',
    title: 'Bathroom Cleaning',
    categoryGroup: 'Cleaning & Sanitization',
    iconName: 'Droplets',
    description: 'Hard water stain removal from shower glass, tile descaling, WC bowl sanitization, and exhaust fan degreasing.',
    commonProblems: ['White hard-water marks on taps and glass', 'Yellow floor tile stains and moldy grout', 'Persistent bathroom odor'],
    priceRange: '₹399 - ₹1,199 (Varies by number of bathrooms)',
    estimatedDuration: '45 - 75 mins per bathroom',
    whatsIncluded: ['Acid-free tile scrubbing', 'Chrome tap & mirror shine restoration', 'Disinfectant WC steam clean'],
  },
  {
    id: 'kitchen-cleaning',
    title: 'Kitchen Cleaning',
    categoryGroup: 'Cleaning & Sanitization',
    iconName: 'Utensils',
    description: 'Oil grease degreasing from tiles, slab scrubbing, exhaust cleaning, sink polishing, and exterior appliance cleaning.',
    commonProblems: ['Sticky oil coating on kitchen walls & cabinets', 'Burnt food stains on countertop', 'Smelly sink drain area'],
    priceRange: '₹799 - ₹2,199 (Varies by kitchen layout)',
    estimatedDuration: '90 - 180 mins',
    whatsIncluded: ['Heavy-duty food-safe degreaser application', 'Cabinet exterior wiping & glass polish', 'Tile scrubbing & sink sanitization'],
  },
  {
    id: 'marble-tile-cleaning',
    title: 'Marble & Tile Cleaning',
    categoryGroup: 'Cleaning & Sanitization',
    iconName: 'Grid',
    description: 'Marble diamond floor polishing, tile grout re-pointing, terrazzo floor scrubbing, and granite seal coating.',
    commonProblems: ['Dull marble floor losing gloss', 'Blackened tile joints/grout lines', 'Scratching & yellowing of stone floor'],
    priceRange: '₹15 - ₹45 per sq ft (Varies by diamond grit stage)',
    estimatedDuration: '4 - 8 hours',
    whatsIncluded: ['Single disc machine diamond pad scrubbing', 'Crystallizer mirror polish application', 'Stain sealant coating'],
  },
  {
    id: 'pest-control',
    title: 'Pest Control',
    categoryGroup: 'Cleaning & Sanitization',
    iconName: 'Bug',
    description: 'Odorless gel & spray pest control for cockroaches, termites, bed bugs, ants, rodents, and mosquitoes.',
    commonProblems: ['Cockroaches in kitchen drawers & cabinets', 'Bed bug bites & blood spots on mattress', 'Termite mud tubes destroying wooden furniture', 'Mosquito breeding near drainages'],
    priceRange: '₹699 - ₹2,999 (Varies by house size & pest type)',
    estimatedDuration: '45 - 90 mins',
    whatsIncluded: ['Bayer odorless herbal gel application', 'Chemical spray in drainages & crevices', 'Free 2nd check visit within 15 days'],
  },

  // Carpentry & Woodwork
  {
    id: 'carpenter',
    title: 'Carpenter',
    categoryGroup: 'Carpentry & Woodwork',
    iconName: 'Hammer',
    badge: 'Top Rated',
    popular: true,
    description: 'Furniture repairs, door alignment, lock fitting, cabinet repairs, modular wardrobe modifications, and custom woodwork.',
    commonProblems: ['Door scraping against floor or frame', 'Loose cabinet hinges or drawer channels', 'Broken bed slats or dining chair legs', 'New shelf or TV unit installation'],
    priceRange: '₹199 - ₹1,299 (Varies by job complexity & wood)',
    estimatedDuration: '30 - 90 mins',
    whatsIncluded: ['Precision levelling & alignment check', 'Quality screws/hinges installation', 'Wood shaving & smoothness sand', 'Dust cleanup'],
  },
  {
    id: 'door-lock-repair',
    title: 'Door Lock Repair',
    categoryGroup: 'Carpentry & Woodwork',
    iconName: 'Lock',
    description: 'Main door mortise lock, godrej lock, digital smart lock, latch repair, key duplication, and handle replacement.',
    commonProblems: ['Key sticking or jammed in lock', 'Door handle loose or sagging', 'Smart lock battery/latch failure', 'Broken lock cylinder'],
    priceRange: '₹249 - ₹999 (Varies by lock type)',
    estimatedDuration: '30 - 60 mins',
    whatsIncluded: ['Cylinder extraction & lubrication', 'Striker plate alignment', 'Latch test with multiple key turns'],
  },
  {
    id: 'furniture-assembly',
    title: 'Furniture Assembly',
    categoryGroup: 'Carpentry & Woodwork',
    iconName: 'Package',
    description: 'Expert assembly of flat-pack furniture from IKEA, Pepperfry, Urban Ladder (beds, wardrobes, tables, shelves).',
    commonProblems: ['Complicated instruction manual', 'Missing screws or specialized tools needed', 'Risk of damaging veneer panels during assembly'],
    priceRange: '₹399 - ₹1,999 (Varies by furniture size)',
    estimatedDuration: '45 - 150 mins',
    whatsIncluded: ['Manual compliance & hardware verification', 'Wall mounting / anchoring for safety', 'Structural stability test'],
  },
  {
    id: 'furniture-repair',
    title: 'Furniture Repair',
    categoryGroup: 'Carpentry & Woodwork',
    iconName: 'Hammer',
    description: 'Wooden chair leg repair, table surface restoration, hydraulic bed lift fix, and loose joints re-gluing.',
    commonProblems: ['Wobbly wooden dining chairs', 'Hydraulic bed storage mechanism stuck', 'Cracked drawer bottoms'],
    priceRange: '₹299 - ₹1,499 (Varies by furniture item)',
    estimatedDuration: '45 - 90 mins',
    whatsIncluded: ['Heavy-duty wood glue & brace reinforcement', 'Hydraulic gas spring testing', 'Surface scratch touch-up'],
  },
  {
    id: 'curtains-blinds',
    title: 'Curtains & Blinds',
    categoryGroup: 'Carpentry & Woodwork',
    iconName: 'Maximize',
    description: 'Curtain rod installation, roller blinds, zebra blinds, Venetian blinds fitting, and motorized blind track setup.',
    commonProblems: ['Wall drill holes damaged', 'Curtain track jammed or uneven', 'Blinds cord snapped or off-pulley'],
    priceRange: '₹199 - ₹899 (Varies by window count)',
    estimatedDuration: '30 - 60 mins',
    whatsIncluded: ['Laser levelling mark', 'Heavy anchor bolt insertion', 'Smooth pulley cord operation test'],
  },
  {
    id: 'modular-kitchen',
    title: 'Modular Kitchen Repair',
    categoryGroup: 'Carpentry & Woodwork',
    iconName: 'Utensils',
    description: 'Tandem drawer channel repair, soft-close hydraulic hinge replacement, kitchen basket alignment, and shutter refurbish.',
    commonProblems: ['Drawers sticking or sagging under weight', 'Kitchen cabinet doors won\'t shut fully', 'Rusted stainless steel wire baskets'],
    priceRange: '₹399 - ₹2,499 (Varies by hardware replaced)',
    estimatedDuration: '60 - 120 mins',
    whatsIncluded: ['German soft-close hardware fitment', 'Shutter gap adjustment', 'Rust-proofing advice'],
  },

  // Painting & Renovations
  {
    id: 'painter',
    title: 'Painting',
    categoryGroup: 'Painting & Renovations',
    iconName: 'PaintBucket',
    popular: true,
    description: 'Interior & exterior wall painting, waterproof coats, texture designs, and wallpaper installation.',
    commonProblems: ['Flaking or peeling wall paint', 'Water dampness marks on living room walls', 'Outdated wall colors needing fresh coats'],
    priceRange: '₹9 - ₹35 per sq ft (Varies by paint grade)',
    estimatedDuration: '1 - 5 days',
    whatsIncluded: ['Laser wall measuring & color consultation', 'Furniture & floor plastic sheeting cover', '2 coats putty + 1 coat primer + 2 coats premium emulsion', 'Post-painting cleanup'],
  },
  {
    id: 'home-renovation',
    title: 'Home Renovation',
    categoryGroup: 'Painting & Renovations',
    iconName: 'Home',
    description: 'Full home remodeling, civil layout changes, modern interior upgrades, tile changing, and structural updates.',
    commonProblems: ['Old outdated house layout', 'Desire for open kitchen or additional bathroom', 'Complete floor and ceiling overhaul'],
    priceRange: 'Custom Quote (Free site inspection & estimate)',
    estimatedDuration: '2 - 6 weeks',
    whatsIncluded: ['3D interior blueprint design', 'Civil demolition & mason work', 'Electrical & plumbing re-wiring', 'Turnkey project manager oversight'],
  },
  {
    id: 'waterproofing',
    title: 'Waterproofing',
    categoryGroup: 'Painting & Renovations',
    iconName: 'Shield',
    description: 'Terrace waterproofing, bathroom dampness coating, chemical injection grouting, and exterior wall sealing.',
    commonProblems: ['Water leaking into rooms below roof terrace', 'Dampness destroying wall plaster', 'Seepage through bathroom tile joints'],
    priceRange: '₹35 - ₹90 per sq ft (Varies by polymer/membrane layer)',
    estimatedDuration: '1 - 3 days',
    whatsIncluded: ['Surface elastomeric coat application', 'Fiberglass mesh reinforcement layer', 'Ponding water test confirmation'],
  },
  {
    id: 'false-ceiling',
    title: 'False Ceiling',
    categoryGroup: 'Painting & Renovations',
    iconName: 'Layers3',
    description: 'Gypsum board false ceiling, POP design execution, cove LED lighting tracks, and acoustic ceiling panels.',
    commonProblems: ['Desire for modern cove lighting', 'Concealing AC ducts and wiring', 'Cracked old POP ceiling design'],
    priceRange: '₹75 - ₹160 per sq ft (Varies by GI channel gauge)',
    estimatedDuration: '2 - 5 days',
    whatsIncluded: ['Rust-proof GI metal framework', 'Saint-Gobain / India Gypsum boards', 'Seamless joint tape & joint compound finish'],
  },
  {
    id: 'mason-work',
    title: 'Mason Work',
    categoryGroup: 'Painting & Renovations',
    iconName: 'HardHat',
    description: 'Brickwork, wall plastering, tile replacing, granite slab fitting, door frame cement fixing, and concrete repair.',
    commonProblems: ['Cracked plaster or hollow wall sound', 'Broken floor or bathroom tiles', 'Granite countertop installation'],
    priceRange: '₹499 - ₹2,999 (Varies by civil work scope)',
    estimatedDuration: '2 - 8 hours',
    whatsIncluded: ['High grade OPC/PPC cement mortar mix', 'Level & plumb line checking', 'Debris bagging & disposal assistance'],
  },
  {
    id: 'tile-glass-repair',
    title: 'Glass & Window Repair',
    categoryGroup: 'Painting & Renovations',
    iconName: 'Maximize',
    description: 'Toughened glass door repair, window pane replacement, sliding glass balcony window roller repair, and mirror fitting.',
    commonProblems: ['Cracked window glass pane', 'Sliding glass door hard to push', 'Shower enclosure glass hinge loose'],
    priceRange: '₹349 - ₹1,799 (Varies by glass thickness)',
    estimatedDuration: '45 - 90 mins',
    whatsIncluded: ['Heavy-duty silicone sealant bead', 'Brass/SS roller replacement', 'Safety glass handling'],
  },
  {
    id: 'welding',
    title: 'Welding Repair',
    categoryGroup: 'Painting & Renovations',
    iconName: 'Zap',
    description: 'Iron gate, window grill, steel railing, shed framework welding repair, and anti-rust primer painting.',
    commonProblems: ['Main gate hinge snapped', 'Balcony safety grill rust break', 'Steel staircase railing loose'],
    priceRange: '₹399 - ₹1,499 (Varies by welding rod count)',
    estimatedDuration: '45 - 90 mins',
    whatsIncluded: ['Electric arc welding joinery', 'Grinding metal slag smooth', 'Red oxide anti-corrosion primer application'],
  },

  // Security, Tech & Power
  {
    id: 'cctv-installation',
    title: 'CCTV Installation',
    categoryGroup: 'Security, Tech & Power',
    iconName: 'Camera',
    description: 'IP & HD CCTV camera setup, DVR/NVR configuration, mobile live remote monitoring, and wire trunking.',
    commonProblems: ['Setting up home security cameras', 'No video signal on CCTV monitor', 'CCTV mobile app connection offline', 'Hard drive recording full/error'],
    priceRange: '₹499 - ₹2,499 (Varies by camera channel count)',
    estimatedDuration: '60 - 180 mins',
    whatsIncluded: ['Camera angle optimization', 'BNC/DC connector crimping', 'Mobile app setup & remote playback test'],
  },
  {
    id: 'home-security',
    title: 'Home Security',
    categoryGroup: 'Security, Tech & Power',
    iconName: 'ShieldCheck',
    description: 'Video door phone, motion sensor alarms, smart door lock sync, and intruder security panel installation.',
    commonProblems: ['Video door phone camera or chime not working', 'Burglar alarm sensor false alerts', 'Integrating smart home locks'],
    priceRange: '₹599 - ₹2,999 (Varies by system complexity)',
    estimatedDuration: '60 - 150 mins',
    whatsIncluded: ['Signal wiring & wireless pairing', 'Volume & sensitivity adjustment', 'User password & RFID card programming'],
  },
  {
    id: 'internet-wifi-setup',
    title: 'Internet & Wi-Fi Setup',
    categoryGroup: 'Security, Tech & Power',
    iconName: 'Wifi',
    description: 'Wi-Fi mesh router setup, Ethernet LAN cable crimping, Wi-Fi dead-zone extension, and network switch configuration.',
    commonProblems: ['Slow Wi-Fi speeds in bedrooms', 'Frequent disconnects or weak router signal', 'LAN port not functioning in study room'],
    priceRange: '₹299 - ₹999 (Varies by mesh count & cabling)',
    estimatedDuration: '30 - 60 mins',
    whatsIncluded: ['RF spectrum channel optimization', 'CAT6 RJ45 termination', 'Bandwidth speed test verification'],
  },
  {
    id: 'inverter-ups-service',
    title: 'Inverter / UPS Service',
    categoryGroup: 'Security, Tech & Power',
    iconName: 'BatteryCharging',
    description: 'Home inverter repair, tubular battery water topping, battery terminal cleaning, and backup load distribution check.',
    commonProblems: ['Inverter not switching to battery mode during outage', 'Battery not holding charge or overheating', 'Beeping warning sound continuously', 'Corrosion on battery terminals'],
    priceRange: '₹249 - ₹999 (Varies by battery distilled water & PCB)',
    estimatedDuration: '30 - 60 mins',
    whatsIncluded: ['Distilled water gravity testing', 'Charging voltage & relay check', 'Petroleum jelly anti-rust terminal coat'],
  },
  {
    id: 'generator-service',
    title: 'Generator Service',
    categoryGroup: 'Security, Tech & Power',
    iconName: 'Cpu',
    description: 'Diesel & petrol generator maintenance, engine oil change, filter replacement, self-starter motor repair, and ATS panel fix.',
    commonProblems: ['Generator failing to crank auto-start', 'Black smoke output or low engine oil', 'Fluctuating voltage output'],
    priceRange: '₹799 - ₹3,499 (Varies by KVA rating)',
    estimatedDuration: '60 - 120 mins',
    whatsIncluded: ['Engine lube oil filter replacement', 'Fuel line bleeding & governor check', 'Load bank output testing'],
  },
  {
    id: 'solar-panel-service',
    title: 'Solar Panel Service',
    categoryGroup: 'Security, Tech & Power',
    iconName: 'Sun',
    description: 'Rooftop solar panel de-ionized water washing, inverter grid tie check, cable junction box inspection, and performance audit.',
    commonProblems: ['Dust accumulation reducing solar generation', 'Solar grid inverter error fault', 'Net meter export count mismatch'],
    priceRange: '₹599 - ₹2,499 (Varies by KW array capacity)',
    estimatedDuration: '60 - 150 mins',
    whatsIncluded: ['Non-abrasive solar glass washing', 'DC voltage & string current check', 'Generation efficiency report'],
  },

  // Shifting & Utility
  {
    id: 'movers-packers',
    title: 'Movers & Packers',
    categoryGroup: 'Shifting & Utility',
    iconName: 'Truck',
    description: 'Intercity and local household goods packing with bubble wrap, corrugated boxes, loading, transportation, and unloading.',
    commonProblems: ['Safe transport of fragile glassware & TV', 'Dismantling heavy furniture and reassembling', 'On-time dedicated covered container vehicle'],
    priceRange: '₹3,500 - ₹18,000 (Varies by volume & distance)',
    estimatedDuration: '4 - 10 hours',
    whatsIncluded: ['3-Layer protective bubble & stretch film wrap', 'Careful loading with hydraulic tailgates', 'Goods transit insurance option'],
  },
  {
    id: 'house-shifting',
    title: 'House Shifting',
    categoryGroup: 'Shifting & Utility',
    iconName: 'Home',
    description: 'Dedicated intra-city house relocation assistance, furniture moving crews, electronics setup, and unpacking support.',
    commonProblems: ['Moving items within the same apartment complex or city', 'Heavy mattress and sofa stair-climbing'],
    priceRange: '₹2,499 - ₹9,999 (Varies by truck size 14ft / 19ft)',
    estimatedDuration: '3 - 6 hours',
    whatsIncluded: ['Professional movers crew', 'Floor & lift protection padding', 'Unpacking & room placement'],
  },
  {
    id: 'gardening',
    title: 'Gardening & Lawn',
    categoryGroup: 'Shifting & Utility',
    iconName: 'Sparkles',
    description: 'Lawn mowing, hedge trimming, plant repotting, organic fertilizer application, and drip irrigation installation.',
    commonProblems: ['Overgrown weeds & lawn grass', 'Pest infestation destroying garden leaves', 'Potted plants wilting'],
    priceRange: '₹399 - ₹1,499 (Varies by garden area sq ft)',
    estimatedDuration: '60 - 180 mins',
    whatsIncluded: ['Grass trimming & dead leaf pruning', 'Soil aeration & neem organic cake addition', 'Debris sweeping'],
  },
  {
    id: 'home-inspection',
    title: 'Home Inspection',
    categoryGroup: 'Shifting & Utility',
    iconName: 'ShieldCheck',
    description: 'Comprehensive 100+ point quality audit for new home possession (thermal leak scan, electrical safety, plumbing pressure, wall hollows).',
    commonProblems: ['Builder handing over property with hidden flaws', 'Undetected wall dampness or faulty wiring before buying', 'Uneven tile slopes causing water pooling'],
    priceRange: '₹3,999 - ₹9,999 (Varies by BHK layout)',
    estimatedDuration: '2 - 4 hours',
    whatsIncluded: ['Infrared thermal camera moisture audit', 'Electrical earth leakage test', 'Detailed digital inspection report with photo evidence'],
  },
];
